
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    generate-ddl: true
    open-in-view: true #enabled, this means that the transaction context is kept open until the end of the web request
  servlet:
    multipart:
      enabled: true
      max-file-size: 3MB
  mail:
    host: smtp.gmail.com
    port: 587
    debug: true
    username: gymstatscol@gmail.com
    password: gymstats123
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  application:
    name: pro-api

filestorage:
  location: C:\Test
logging:
  level:
    org:
    ##springframework: DEBUG
    web: debug
my:
  uuid: ${random:uuid}
management:
  server:
    port: 8081
  endpoints:
    web:
      exposure:
        include: "*"
