version: "3"
services:
  pro-api:
    container_name: pro-api
    build: .
    expose:
      - 8080
    ports:
      - "8080:8080"
    depends_on:
      - apidb
  apidb:
    image: postgres
    expose:
      - 5432
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: lego
      POSTGRES_USER: lego

